### ISSUE TITLE
Colour page lacks colour and is spelt wrong

### ISSUE THREAD

**Issue by BubbleShade** [SketchedDoughnut/SketchedDoughnut#1]
The top link on the website, which goes to the "color" page, is misleading as it leads the user into a pitch black page, devoid of life. This can cause issues as the user may expect a vibrant page bursting with colour. Not only that, but the link also misspells "colour" as "color".
plz fix

**Comment by SketchedDoughnut** [comment]
The dark void, devoid of life is necessary. However, it has been renamed to "colour".
